Disable WARNING_AS_ERROR by default
BlueBrain/libsonatareport pull request #4
Opened 2021-02-04 08:16 UTC by alkino

2021-02-04 08:24 UTC, pramodk requested changes

2021-02-04 08:24 UTC, pramodk commented on CMakeLists.txt
> +endif()
We should check compiler id here before adding flags? (as reference, see [here](https://github.com/neuronsimulator/nrn/blob/ee63557e2b3728c0a61547bb18c929b596b2d516/cmake/CompilerFlagsHelpers.cmake#L14))

2021-02-04 08:30 UTC, pramodk commented on CMakeLists.txt
> +endif()
By the way, nrn cmake was derived from [highfive](https://github.com/BlueBrain/HighFive/blob/master/CMake/config/CompilerFlagsHelpers.cmake). I don't think we need detailed one like that but there should be minimum check before inserting a compiler flag.

2021-02-05 10:53 UTC, alkino commented
Already merged

2021-02-05 10:54 UTC, closed without merging